### ISSUE TITLE
BOARD_KERNEL_IMAGE_NAME is not set in BoardConfig.mk

### ISSUE THREAD

**Issue by AliceGrey** [SebaUbuntu/TWRP-device-tree-generator#19]
```
[ 99% 396/397] finishing build rules ...
FAILED: 
vendor/omni/build/tasks/kernel.mk:94: error: BOARD_KERNEL_IMAGE_NAME not defined..
11:36:19 ckati failed with: exit status 1

#### failed to build some targets (01:24 (mm:ss)) ####
```
The tree generator should probably set this value. I was able to get it to build by manually setting the value in BoardConfig.mk

**Comment by SebaUbuntu** [comment]
https://github.com/SebaUbuntu/TWRP-device-tree-generator/commit/b79aa6078d24125bd5e03de7a2ad5d79b71efa15
Fixed
