### ISSUE TITLE
Can't unpack if magic and androidbootimg.magic are in windows langage

### ISSUE THREAD

**Issue by Elenedeath** [SebaUbuntu/TWRP-device-tree-generator#21]
Hello i post you an issue and how to resolve it. i investigate and see what the problem and how to correct.

I clone your repository on windows and use py -m twrpdtgen TWRP331-BV9900_Android9-2019.img
For me py are python3 and python are for python2
![Screenshot_1](https://user-images.githubusercontent.com/502132/97236133-b87b4200-17e4-11eb-8b19-367d46a46579.png)

After this i manually catch AIK from your repo and unzip in folder extract and try like this, oh nice it's working.

i compare with WinMerge original AIK and my github zip from your repo and see this
![Screenshot_2](https://user-images.githubusercontent.com/502132/97235954-528eba80-17e4-11eb-8d7d-45fac9ccc904.png)

Due to this i search what the difference and all this file have something common, all are encoded in windows where other files are encoded on unix.

![Screenshot_6](https://user-images.githubusercontent.com/502132/97236291-13ad3480-17e5-11eb-8a44-e7908287c8ad.png)

Simple fix and the really blocking file are 'androidbootimg.magic' and 'magic' need to changed to unix encoding and after this work fine.

This is the error when 'magic' file are unix encode but 'androidbootimg.magic' file are windows
![Screenshot_9](https://user-images.githubusercontent.com/502132/97236382-45be9680-17e5-11eb-8a50-e3f5b450f385.png)

This is the error when 'magic' file are windows encode but 'androidbootimg.magic' file are unix
![Screenshot_8](https://user-images.githubusercontent.com/502132/97236406-5cfd8400-17e5-11eb-8646-ce04e33629b1.png)

**Comment by SebaUbuntu** [comment]
AIK-Windows-mirror has been force pushed with both files with LF line endings, please retry

**Comment by Elenedeath** [comment]
i try and didn't change, he changed previous files to CR+LF
