### ISSUE TITLE
my device build.prop dont have ro.board.platform=

### ISSUE THREAD

**Issue by slhrlx** [SebaUbuntu/TWRP-device-tree-generator#31]
Hi, i tried use de script, but, Always i go to create device-tree i get one error that says "ro.board.platform", and i go check my build.prop, and he dont have | ro.board.platform

Some Samsung devices have this problem, i checked on two more devices on my house

my build.prop:https://drive.google.com/file/d/102zc-4v4N9EkZ7VpU2Lg85GfPuwU2TLs/view?usp=drivesdk

stock recovery:https://drive.google.com/file/d/105n506bNQVDVFAKoakC6Ao-2lLSMgQgV/view?usp=drivesdk

**Comment by SebaUbuntu** [comment]
Fixed with latest commit https://github.com/SebaUbuntu/TWRP-device-tree-generator/commit/7041f588b91649b54de49478ba2f36bc4c044911
