### ISSUE TITLE
Creates a Problem while Allocating Path

### ISSUE THREAD

**Issue by ShahrukhAbrar** [SebaUbuntu/TWRP-device-tree-generator#34]
When creating a device tree for me it created a path "tecno spark lite" while linux doesnt read path like this and the path is only read as tecno. Causing error during the build.

**Comment by SebaUbuntu** [comment]
Please send the recovery image you used

**Comment by ShahrukhAbrar** [comment]
> Please send the recovery image you used


[recovery.img.zip](https://github.com/SebaUbuntu/TWRP-device-tree-generator/files/5761628/recovery.img.zip)

Here you go.

**Comment by SebaUbuntu** [comment]
Fixed with commit 1daafcf12293089acda0a0f9b33d7650e561aa0f
