### ISSUE TITLE
mkbootimg: error: unrecognized arguments: --dtb device/xiaomi/vayu/prebuilt/dtb.img

### ISSUE THREAD

**Issue by kiam001** [SebaUbuntu/TWRP-device-tree-generator#57]
hello, i have a build error 

mkbootimg: error: unrecognized arguments: --dtb device/xiaomi/vayu/prebuilt/dtb.img 

on tree https://github.com/kiam001/twrp_device_xiaomi_vayu 

jenkins full log https://jenkins.home.kiam001.tk/job/recovery_vayu/3/console

**Comment by kiam001** [comment]
on 10 manifests Works

**Comment by wwaaafa** [comment]
https://github.com/LineageOS/android_system_core/tree/lineage-17.1/mkbootimg
is support --dt
