### ISSUE TITLE
[question] How to get a recovery image?

### ISSUE THREAD

**Issue by erik9012** [SebaUbuntu/TWRP-device-tree-generator#60]
Which ways exists to get a recovery image for a smartphone? This would be nice to know so I can generate a twrp build.

**Comment by FrosT2k5** [comment]
> Which ways exists to get a recovery image for a smartphone? This would be nice to know so I can generate a twrp build.

You can get it from the zip of your device official firmware. You'll have to extract it from there

**Comment by erik9012** [comment]
Thanks
