### ISSUE TITLE
AssertionError: Property ro.product.cpu.abi could not be found in build.prop

### ISSUE THREAD

**Issue by Vloupmon** [SebaUbuntu/TWRP-device-tree-generator#85]
The script crashes on failing to find a `ro.product.cpu.abi` property in the build.prop file.

My understanding is that `ro.product.cpu.abi` is in fact deprecated, and `ro.product.cpu.abilist` is the current
property name. `ro.product.cpu.abilist` lists the supported ABIs in descending order of feature-richness.

That's how my ROMs build.prop file looks like :

`> cat recovery/ramdisk/vendor/build.prop | grep cpu`
`ro.vendor.product.cpu.abilist=arm64-v8a,armeabi-v7a,armeabi`
`ro.vendor.product.cpu.abilist32=armeabi-v7a,armeabi`
`ro.vendor.product.cpu.abilist64=arm64-v8a`

Adding `ro.product.cpu.abi=arm64-v8a` to the build.prop file allows the script to continue.

Fix idea : Check if `ro.product.cpu.abilist` / `ro.vendor.product.cpu.abilist` exists, if it does pick the leftmost property. Otherwise look for `ro.product.cpu.abi`.

**Comment by SebaUbuntu** [comment]
Fixed with latest release
