### ISSUE TITLE
some errors occurred

### ISSUE THREAD

**Issue by shaw99** [SebaUbuntu/TWRP-device-tree-generator#88]
shaw@ubuntu:~/TWRP-device-tree-generator-master$ python3 -m twrpdtgen '/home/shaw/Desktop/11/669boot.img' 
TWRP device tree generator
Version 2.0.1

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/shaw/TWRP-device-tree-generator-master/twrpdtgen/__main__.py", line 6, in <module>
    main()
  File "/home/shaw/TWRP-device-tree-generator-master/twrpdtgen/main.py", line 31, in main
    device_tree = DeviceTree(image=args.image, debug=args.debug)
  File "/home/shaw/TWRP-device-tree-generator-master/twrpdtgen/devicetree.py", line 49, in __init__
    self.aik = AIKManager(image, debug=debug)
  File "/home/shaw/TWRP-device-tree-generator-master/twrpdtgen/utils/aikmanager.py", line 74, in __init__
    raise RuntimeError(f"AIK extraction failed, return code {returncode}")
RuntimeError: AIK extraction failed, return code 1

**Comment by xxroot** [comment]
网络的问题，能访问github.com就可以了

**Comment by SebaUbuntu** [comment]
> shaw@ubuntu:~/TWRP-device-tree-generator-master$ python3 -m twrpdtgen '/home/shaw/Desktop/11/669boot.img' TWRP device tree generator Version 2.0.1
> 
> Traceback (most recent call last): File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main return _run_code(code, main_globals, None, File "/usr/lib/python3.8/runpy.py", line 87, in _run_code exec(code, run_globals) File "/home/shaw/TWRP-device-tree-generator-master/twrpdtgen/**main**.py", line 6, in main() File "/home/shaw/TWRP-device-tree-generator-master/twrpdtgen/main.py", line 31, in main device_tree = DeviceTree(image=args.image, debug=args.debug) File "/home/shaw/TWRP-device-tree-generator-master/twrpdtgen/devicetree.py", line 49, in **init** self.aik = AIKManager(image, debug=debug) File "/home/shaw/TWRP-device-tree-generator-master/twrpdtgen/utils/aikmanager.py", line 74, in **init** raise RuntimeError(f"AIK extraction failed, return code {returncode}") RuntimeError: AIK extraction failed, return code 1

Report this issue to osm0sis
